name: Continuous Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Generate plugins database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          lfs: true
      - name: Create Plugin Database
        run: kotlin ci/create-plugin-database.main.kts

      - name: 📂 SFTP upload to omegat.org
        uses: wangyucode/sftp-upload-action@v2.0.2
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.SOURCEFORGE_WEB_USER }}
          password: ${{ secrets.SOURCEFORGE_WEB_PASS }}
          host: 'web.sourceforge.net'
          forceUpload: true
          local_path: "${{github.workspace}}/build/dist/plugins.json"
          remote_path: '/home/project-web/omegat/htdocs/plugins'
          sftpArgs: '-o ConnectTimeout=5'
