name: Continuous Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Generate plugins database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          lfs: true
      - name: Create Plugin Database
        run: kotlin ci/create-plugin-database.main.kts

      - name: Update Tag
        if: github.ref == 'refs/heads/main'
        run: |
          git tag --force continuous-release ${GITHUB_SHA}
          git push --force --tags

      - name: Update Continuous Release
        if: github.ref == 'refs/heads/main'
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{github.workspace}}/build/plugins.json
          release: Continuous Release
          tag: continuous-release

